---
title: '2'
output: html_document
date: "2024-03-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r,warning=FALSE,message=FALSE}
library(sp)
library(gstat)
```

```{r,warning=FALSE,message=FALSE}
data(meuse)
class(meuse)
```

```{r,warning=FALSE,message=FALSE}
names(meuse)

```

```{r,warning=FALSE,message=FALSE}
str(meuse)
```

```{r,warning=FALSE,message=FALSE}
summary(meuse)

```

```{r,warning=FALSE,message=FALSE}
coordinates(meuse) = ~x+y
class(meuse)
```

```{r,warning=FALSE,message=FALSE}
summary(meuse)
```

```{r,warning=FALSE,message=FALSE}
names(meuse)
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```

```{r,warning=FALSE,message=FALSE}
```
