---
title: '2'
output:
  html_document:
    toc: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load necessary libraries
```{r,warning=FALSE,message=FALSE}
library(gstat)
library(tidyverse)
library(viridis)
library(sp)
library(sf)
library(stars)
library(patchwork)
library(ggplot2)
```

##loads the dataset named "meuse" into the current R session.check the data type. show the head
```{r,warning=FALSE,message=FALSE}
data(meuse)
```


```{r,warning=FALSE,message=FALSE}
data(meuse)
class(meuse)
head(meuse)
```

# Load necessary libraries
```{r,warning=FALSE,message=FALSE}
library(gstat)
library(tidyverse)
library(viridis)
library(sp)
library(sf)
library(stars)
library(patchwork)
library(ggplot2)
```
```{r,warning=FALSE,message=FALSE}
data(meuse)
class(meuse)
head(meuse)
```

# Load necessary libraries
```{r,warning=FALSE,message=FALSE}
library(gstat)
library(tidyverse)
library(viridis)
library(sp)
library(sf)
library(stars)
library(patchwork)
library(ggplot2)
```

