#!C:\Users\Pragiya\Desktop\MSC\Spatio-Temporral\Assingment2\Question02\working\myenv\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
